In [22]:
!pip install google-auth-oauthlib google-api-python-client pandas

Requirement already satisfied: google-auth-oauthlib in /opt/anaconda3/lib/python3.13/site-packages (1.4.0)
Requirement already satisfied: google-api-python-client in /opt/anaconda3/lib/python3.13/site-packages (2.196.0)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: google-auth!=2.43.0,!=2.44.0,!=2.45.0,<3.0.0,>=2.15.0 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth-oauthlib) (2.53.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth-oauthlib) (2.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth!=2.43.0,!=2.44.0,!=2.45.0,<3.0.0,>=2.15.0->google-auth-oauthlib) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth!=2.43.0,!=2.44.0,!=2.45.0,<3.0.0,>=2.15.0->google-auth-oauthlib) (46.0.3)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-python-client) (0.31.2)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-python-client) (0.4.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-python-client) (2.30.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-python-client) (4.2.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (5.29.3)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.28.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.5)
Requirement already satisfied: pyparsing<4,>=3.1 in /opt/anaconda3/lib/python3.13/site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.2.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2025.11.12)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=38.0.3->google-auth!=2.43.0,!=2.44.0,!=2.45.0,<3.0.0,>=2.15.0->google-auth-oauthlib) (2.0.0)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth!=2.43.0,!=2.44.0,!=2.45.0,<3.0.0,>=2.15.0->google-auth-oauthlib) (2.23)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/anaconda3/lib/python3.13/site-packages (from pyasn1-modules>=0.2.1->google-auth!=2.43.0,!=2.44.0,!=2.45.0,<3.0.0,>=2.15.0->google-auth-oauthlib) (0.6.1)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.3.1)

In [23]:
import os
import pickle
from datetime import datetime
import pandas as pd
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from google.auth.transport.requests import Request

# Strict required scopes for accessing standard profiles and directory metadata cards
SCOPES = [
    'https://www.googleapis.com/auth/userinfo.profile',
    'https://www.googleapis.com/auth/user.birthday.read',
    'https://www.googleapis.com/auth/user.phonenumbers.read',
    'https://www.googleapis.com/auth/user.gender.read'
]

def get_people_service():
    """Handles OAuth 2.0 validation lifecycle cleanly."""
    creds = None
    if os.path.exists('profile_token.pickle'):
        with open('profile_token.pickle', 'rb') as token:
            creds = pickle.load(token)
            
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists('credentials.json'):
                raise FileNotFoundError("Missing 'credentials.json' in your local directory.")
            flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        with open('profile_token.pickle', 'wb') as token:
            pickle.dump(creds, token)
            
    return build('people', 'v1', credentials=creds)

def calculate_age(birthday_dict):
    """Calculates age in years relative to the active target calendar date."""
    if not birthday_dict:
        return "N/A"
    year = birthday_dict.get('year')
    month = birthday_dict.get('month')
    day = birthday_dict.get('day')
    if not year or not month or not day:
        return "N/A (Year Hidden)"
    today = datetime.today()
    try:
        birth_date = datetime(year, month, day)
        age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))
        return int(age)
    except Exception:
        return "N/A"

def fetch_user_profile():
    """
    Extracts complete account info by cross-referencing standard user profile endpoints
    with batch directory lookups to retrieve hidden recovery mobile numbers.
    """
    service = get_people_service()
    
    print("Resolving authenticated identity vectors...")
    
    # 1. Fetch primary profile card layout
    profile = service.people().get(
        resourceName='people/me',
        personFields='names,phoneNumbers,birthdays,genders'
    ).execute()
    
    # Parse Names
    first_name, last_name = "N/A", "N/A"
    names = profile.get('names', [])
    if names:
        first_name = names[0].get('givenName', 'N/A')
        last_name = names[0].get('familyName', 'N/A')
        
    # Parse Gender
    gender = "N/A"
    genders = profile.get('genders', [])
    if genders:
        gender = genders[0].get('formattedValue', 'N/A')
        
    # Parse Birthday / Age
    dob_string, age = "N/A", "N/A"
    birthdays = profile.get('birthdays', [])
    if birthdays:
        date_data = birthdays[0].get('date', {})
        if date_data:
            day = date_data.get('day', '')
            month = date_data.get('month', '')
            year = date_data.get('year', '')
            dob_string = f"{day:02d}/{month:02d}/{year}" if year else f"{day:02d}/{month:02d}"
            age = calculate_age(date_data)

    # 2. Extract Phone Numbers using standard fallback arrays first
    found_numbers = []
    phone_numbers = profile.get('phoneNumbers', [])
    for p in phone_numbers:
        val = p.get('value') or p.get('canonicalForm')
        if val and val not in found_numbers:
            found_numbers.append(val)

    # 3. CRITICAL DEEP SEARCH: Run batch lookup to pull recovery/account security configurations
    try:
        # Retrieve primary profile string via directory discovery
        directory_res = service.people().get(
            resourceName='people/me',
            personFields='metadata'
        ).execute()
        
        source_id = directory_res.get('metadata', {}).get('sources', [{}])[0].get('id')
        
        if source_id:
            # Re-query system matrix using cross-directory batch scopes
            batch_res = service.people().batchGet(
                resourceNames=[f'people/{source_id}'],
                personFields='phoneNumbers'
            ).execute()
            
            responses = batch_res.get('responses', [])
            if responses:
                deep_person = responses[0].get('person', {})
                deep_phones = deep_person.get('phoneNumbers', [])
                for dp in deep_phones:
                    dval = dp.get('value') or dp.get('canonicalForm')
                    if dval and dval not in found_numbers:
                        found_numbers.append(dval)
    except Exception:
        pass # Handle strict sandbox directory blocks gracefully

    # Format numbers nicely for the DataFrame column display
    mobile_number = " | ".join(found_numbers) if found_numbers else "N/A"
        
    user_matrix = [{
        'First Name': first_name,
        'Last Name': last_name,
        'Mobile Number': mobile_number,
        'Date of Birth': dob_string,
        'Age (Years)': age,
        'Gender': gender
    }]
    
    return pd.DataFrame(user_matrix)

if __name__ == "__main__":
    df_profile = fetch_user_profile()
    print("\n[SUCCESS] Profile details completely populated:")
    df_profile

Resolving authenticated identity vectors...

[SUCCESS] Profile details completely populated:

In [24]:
df_profile

  First Name Last Name Mobile Number Date of Birth  Age (Years) Gender
0     Anwesh    Biswas           N/A    30/03/2001           25   Male

In [25]:
!pip install pypdf

Requirement already satisfied: pypdf in /opt/anaconda3/lib/python3.13/site-packages (6.11.0)

In [26]:
import os
import pickle
import re
import base64
import io
import pandas as pd
from bs4 import BeautifulSoup
from pypdf import PdfReader
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from google.auth.transport.requests import Request

SCOPES = ['https://www.googleapis.com/auth/gmail.readonly']

def get_gmail_service():
    """Manages the OAuth 2.0 lifecycle using a local Desktop Client context."""
    creds = None
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists('credentials.json'):
                raise FileNotFoundError("Missing 'credentials.json' in your local directory.")
            flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)
    return build('gmail', 'v1', credentials=creds)

def extract_all_body_and_attachments(service, message_id, payload):
    """Linearly flattens MIME trees and handles structural PDF layout byte extraction."""
    html_text = ""
    pdf_text = ""
    stack = [payload]
    
    while stack:
        current_part = stack.pop()
        mime_type = current_part.get('mimeType', '')
        filename = current_part.get('filename', '')
        
        if 'parts' in current_part:
            stack.extend(current_part['parts'])
            continue
            
        if mime_type in ['text/plain', 'text/html'] and not filename:
            data = current_part.get('body', {}).get('data', '')
            if data:
                decoded_str = base64.urlsafe_b64decode(data.encode('ASCII')).decode('utf-8', errors='ignore')
                html_text += " " + decoded_str
                
        elif filename.lower().endswith('.pdf') or mime_type == 'application/pdf':
            attachment_id = current_part.get('body', {}).get('attachmentId')
            if attachment_id:
                try:
                    attachment = service.users().messages().attachments().get(
                        userId='me', messageId=message_id, id=attachment_id
                    ).execute()
                    file_data = base64.urlsafe_b64decode(attachment['data'].encode('UTF-8'))
                    
                    pdf_io = io.BytesIO(file_data)
                    reader = PdfReader(pdf_io)
                    for page in reader.pages:
                        extracted = page.extract_text()
                        if extracted:
                            pdf_text += extracted + "\n"
                except Exception:
                    pass 
                    
    return html_text, pdf_text

def parse_transaction_data(combined_text, sender, subject):
    """
    Advanced parsing matrix with strict financial intent validation.
    Bypasses status updates to block numerical tracking leaks.
    """
    sender_lower = sender.lower()
    subject_lower = subject.lower()
    brand_name = re.sub(r'\s*<.*?>', '', sender).replace('"', '').replace("'", "").strip()
    
    # Check if the email context is strictly a tracking or delivery status update
    is_transit_status = any(k in subject_lower or k in combined_text.lower() for k in [
        "packed", "out for delivery", "reached your city", "arriving early", "has been delivered", "shipment"
    ])
    
    amount = "N/A"
    normalized_text = re.sub(r'\s+', ' ', combined_text)
    
    # --- Custom Precision Match Protocols ---
    if "eatclub" in sender_lower:
        match = re.search(r'(?:Online Paid|Grand Total|Total|Sub Total)[:\s]*[₹Rs\.?]*\s*([\d,]+\.\d{2})', normalized_text, re.IGNORECASE)
        if match:
            amount = f"₹ {match.group(1)}"
            
    elif "namecheap" in sender_lower:
        # Pulls valid totals including $0.00 summaries accurately
        match = re.search(r'(?:Total|Charged|Amount)[:\s]*(?:US\s*\$|\$)\s*([\d,]+\.\d{2})', normalized_text, re.IGNORECASE)
        if match:
            amount = f"$ {match.group(1)}"

    elif "phonepe" in sender_lower:
        match = re.search(r'(?:Transaction Value|Amount|Paid)[:\s]*[₹Rs\.?]*\s*([\d,]+(?:\.\d{2})?)', normalized_text, re.IGNORECASE)
        if match:
            amount = f"₹ {match.group(1)}"

    elif "axis" in sender_lower:
        match = re.search(r'(?:debited for|spent|amount of|INR)[:\s]*INR\s*([\d,]+\.\d{2})', normalized_text, re.IGNORECASE)
        if match:
            amount = f"₹ {match.group(1)}"

    elif "shiprocket" in sender_lower:
        # Scan explicitly for clear financial indicators only
        match = re.search(r'(?:Invoice Total|Amount Paid|Total Amount|Paid Total)[:\s]*[₹Rs\.?]*\s*\b(\d+(?:\.\d{2})?)\b', normalized_text, re.IGNORECASE)
        if match:
            amount = f"₹ {match.group(1)}"
        elif is_transit_status:
            # Drop transit markers completely to avoid picking up arbitrary IDs
            return brand_name, "N/A", "N/A"

    # Global Fallback Matrix Engine
    if amount == "N/A" and not is_transit_status:
        global_patterns = [
            r'(?:Total|Amount|Paid|Net Payable)[:\s]*.*?([₹$]|Rs\.?|INR)\s*([\d,]+\.\d{2})',
            r'(?:Total Amount|Grand Total|Total)[:\s]*[₹Rs]*\s*\b(\d+(?:\.\d{2})?)\b',
            r'([₹$])\s*([\d,]+\.\d{2})'
        ]
        for pattern in global_patterns:
            match = re.search(pattern, normalized_text, re.IGNORECASE)
            if match:
                if len(match.groups()) > 1:
                    val = match.group(2)
                    sym = match.group(1)
                    if val not in ["1", "2"]: # Ignore baseline indexing metrics
                        amount = f"{sym} {val}".strip()
                        break
                else:
                    val = match.group(1)
                    if val not in ["1", "2"]:
                        amount = f"₹ {val}"
                        break

    # --- Item Description Logic ---
    item_details = "N/A"
    if "eatclub" in sender_lower and "product details" in combined_text.lower():
        lines = combined_text.split('\n')
        captured = []
        start = False
        for line in lines:
            if any(k in line.lower() for k in ["product details", "item description"]):
                start = True
                continue
            if start:
                if any(k in line.lower() for k in ["sub total", "total", "customer details", "order information"]):
                    break
                cleaned = re.sub(r'\s+', ' ', line).strip()
                if cleaned and not cleaned.replace('.', '').isdigit() and len(cleaned) > 3:
                    if not any(x in cleaned.lower() for x in ["qty", "rate", "amount"]):
                        captured.append(cleaned)
        if captured:
            item_details = " | ".join(captured[:3])

    if item_details == "N/A":
        subject_cleaned = re.sub(r'(Order Confirmed:|Your order|Invoice for|Receipt for|Your delivery from|Your purchase|Confirmed|Booking|#\d+|\d+)', '', subject, flags=re.IGNORECASE).strip()
        if len(subject_cleaned) > 5 and not any(x in subject_cleaned.lower() for x in ['successful', 'payment', 'thank you', 'alert']):
            item_details = subject_cleaned
        else:
            item_details = subject.strip()

    return brand_name, amount, item_details

def execute_perfect_scanner(service):
    emails_data = []
    
    # We restrict search constraints to catch concrete ledger items
    query = 'category:purchases OR from:noreply@phonepe.com OR from:alerts@axis.bank.in OR from:info@net.shiprocket.in'
    
    print("Connecting securely to Gmail Engine API...")
    response = service.users().messages().list(userId='me', q=query).execute()
    messages = response.get('messages', [])

    while 'nextPageToken' in response:
        page_token = response['nextPageToken']
        response = service.users().messages().list(userId='me', q=query, pageToken=page_token).execute()
        messages.extend(response.get('messages', []))

    total = len(messages)
    print(f"Sync complete. Running extraction filters over {total} metadata elements...")

    for idx, msg in enumerate(messages):
        try:
            msg_detail = service.users().messages().get(userId='me', id=msg['id'], format='full').execute()
            payload = msg_detail.get('payload', {})
            headers = payload.get('headers', [])
            snippet = msg_detail.get('snippet', '')
            
            subject = next((h['value'] for h in headers if h['name'].lower() == 'subject'), '(No Subject)')
            sender = next((h['value'] for h in headers if h['name'].lower() == 'from'), '(Unknown Sender)')
            date = next((h['value'] for h in headers if h['name'].lower() == 'date'), '(Unknown Date)')
            
            html_content, pdf_content = extract_all_body_and_attachments(service, msg['id'], payload)
            
            soup = BeautifulSoup(html_content, 'html.parser')
            clean_html_text = soup.get_text(separator=' ').strip()
            
            unified_corpus = f"{clean_html_text}\n{snippet}\n{pdf_content}"
            
            brand, amount, description = parse_transaction_data(unified_corpus, sender, subject)
            clean_date = re.sub(r'([\+\s-]\d{4}.*)$', '', date).strip()

            if amount != "N/A":
                emails_data.append({
                    'Brand Name': brand,
                    'Amount': amount,
                    'Item / Description': description,
                    'Date of Transaction': clean_date,
                    'Sender Email ID': sender
                })
            
        except Exception:
            pass 
            
        if (idx + 1) % 20 == 0 or (idx + 1) % total == 0:
            print(f"Processed structural validation checks for {idx + 1}/{total} items...")
            
    return emails_data

if __name__ == "__main__":
    gmail_service = get_gmail_service()
    dataset_list = execute_perfect_scanner(gmail_service)
    
    df_purchases = pd.DataFrame(dataset_list)
    
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.max_colwidth', None)
    
    print(f"\n[SUCCESS] Extraction complete. Displaying filtered purchase data matrix:")
    df_purchases

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=845760680388-gvfkujfv85of7b4n4it5a6mvaq2nqa7q.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A53788%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.readonly&state=sZ4gmZseGLeyAphX4YZcurN4ONF4IS&code_challenge=4GMg2xqPH-6vYJPk-tYpgl77PGGG1U-UAjiuhZBC45A&code_challenge_method=S256&access_type=offline
Connecting securely to Gmail Engine API...
Sync complete. Running extraction filters over 186 metadata elements...
Processed structural validation checks for 20/186 items...
Processed structural validation checks for 40/186 items...
Processed structural validation checks for 60/186 items...
Processed structural validation checks for 80/186 items...
Processed structural validation checks for 100/186 items...
Processed structural validation checks for 120/186 items...
Processed structural validation checks for 140/186 items...
Processed structural validation checks for 160/186 items...
Processed structural validation checks for 180/186 items...
Processed structural validation checks for 186/186 items...

[SUCCESS] Extraction complete. Displaying filtered purchase data matrix:

In [27]:
# 1. Remove display limits for rows and column content width
pd.set_option('display.max_rows', None)          # Tells pandas to display every single row
pd.set_option('display.max_columns', None)       # Tells pandas to show all columns without truncating
pd.set_option('display.max_colwidth', None)      # Prevents long item texts from getting cut off with '...'

# 2. Render the full dataframe
df_purchases

                    Brand Name        Amount                                                                                                                                                    Item / Description Date of Transaction                                  Sender Email ID
0             Axis Bank Alerts    INR 139.00                                                                                                                                        Upcoming AutoPay txn. reminder         Sat, 16 May           Axis Bank Alerts <alerts@axis.bank.in>
1          alerts@axis.bank.in    INR 199.00                                                                                                                                        Upcoming AutoPay txn. reminder         Tue, 12 May      "alerts@axis.bank.in" <alerts@axis.bank.in>
2           Namecheap Renewals       $ 39.18                                                                                                                anwesh, your domains will expire in  hours - renew now         Fri, 08 May      Namecheap Renewals <renewals@namecheap.com>
3           Namecheap Renewals       $ 39.18                                                                                                                 anwesh, your domains will expire in  days - renew now         Sat, 02 May      Namecheap Renewals <renewals@namecheap.com>
4           Namecheap Renewals       $ 39.18                                                                                                                 anwesh, your domains will expire in  days - renew now         Fri, 24 Apr      Namecheap Renewals <renewals@namecheap.com>
5                     Payments      ₹ 263.69                                                                                                                                         Payment successful for OFFLYN         Sun, 19 Apr                 Payments <no-reply@razorpay.com>
6                      Eatclub      ₹ 328.00                                                                           Garden Harvest Pizza - Regular (7") | Thin Crust Cheese Blast, Mushrooms | 1 Pc 328.0 328.0         Tue, 14 Apr                     Eatclub <noreply@eatclub.in>
7           Namecheap Renewals       $ 39.18                                                                                                                 anwesh, your domains will expire in  days - renew now         Thu, 09 Apr      Namecheap Renewals <renewals@namecheap.com>
8           Namecheap Renewals       $ 23.18                                                                                                                 anwesh, goswipe.app will expire in  hours - renew now         Mon, 30 Mar      Namecheap Renewals <renewals@namecheap.com>
9            Namecheap Support        $ 0.00                                                                                                                                    Namecheap Order Summary (Order# );         Sun, 29 Mar        Namecheap Support <support@namecheap.com>
10          Namecheap Renewals       $ 23.18                                                                                                                  anwesh, goswipe.app will expire in  days - renew now         Tue, 24 Mar      Namecheap Renewals <renewals@namecheap.com>
11          Namecheap Renewals       $ 23.18                                                                                                                  anwesh, goswipe.app will expire in  days - renew now         Mon, 16 Mar      Namecheap Renewals <renewals@namecheap.com>
12                     Eatclub      ₹ 268.00                                                                                         Ghee Dal Khichdi Meal 1 Pc 229.0 229.0 | Masala Chaas [200 ml] 1 Pc 39.0 39.0         Sat, 14 Mar                     Eatclub <noreply@eatclub.in>
13                    Tata 1mg        ₹ 1589                                                                                                                                                         Order ID: PO-         Fri, 13 Mar                 Tata 1mg <no-reply@mail.1mg.com>
14                     Eatclub      ₹ 359.00                                                                                                        Herb Chicken Mighty Bowl [64g - High Protein] 1 Pc 359.0 359.0         Thu, 12 Mar                     Eatclub <noreply@eatclub.in>
15                    Payments      ₹ 696.00                                                                                                                  Payment successful for BATRA NUMERRO PRIVATE LIMITED         Thu, 12 Mar                 Payments <no-reply@razorpay.com>
16                    Tata 1mg   Rs. 1399.00                                                                                                                                                  with Tata mg Labs is         Wed, 11 Mar                 Tata 1mg <no-reply@mail.1mg.com>
17                    Payments     ₹ 1345.00                                                                                                       Payment successful for 1MG HEALTHCARE SOLUTIONS PRIVATE LIMITED         Wed, 11 Mar                 Payments <no-reply@razorpay.com>
18                    Tata 1mg         ₹ 122                                                                                                                                   Your test reports are now available         Thu, 05 Mar                 Tata 1mg <no-reply@mail.1mg.com>
19                    Tata 1mg         ₹ 125                                                                                                                                   Your test reports are now available         Thu, 05 Mar                 Tata 1mg <no-reply@mail.1mg.com>
20                    Tata 1mg        ₹ 2087                                                                                                                                                         Order ID: PO-         Thu, 05 Mar                 Tata 1mg <no-reply@mail.1mg.com>
21                    Tata 1mg        ₹ 1998                                                                                                                                                         Order ID: PO-         Thu, 05 Mar                 Tata 1mg <no-reply@mail.1mg.com>
22                    Tata 1mg         ₹ 185                                                                                                                                   Your test reports are now available         Thu, 05 Mar                 Tata 1mg <no-reply@mail.1mg.com>
23                    Tata 1mg        ₹ 4498                                                                                                                                                         Order ID: PO-         Thu, 05 Mar                 Tata 1mg <no-reply@mail.1mg.com>
24                    Tata 1mg    Rs. 799.00                                                                                                                 Sample collection date/time updated for Order ID: PO-         Tue, 03 Mar                 Tata 1mg <no-reply@mail.1mg.com>
25                    Tata 1mg    Rs. 799.00                                                                                                                 Sample collection date/time updated for Order ID: PO-         Tue, 03 Mar                 Tata 1mg <no-reply@mail.1mg.com>
26                    Tata 1mg   Rs. 1999.00                                                                                                                 Sample collection date/time updated for Order ID: PO-         Tue, 03 Mar                 Tata 1mg <no-reply@mail.1mg.com>
27                    Tata 1mg    Rs. 799.00                                                                                                                                                  with Tata mg Labs is         Tue, 03 Mar                 Tata 1mg <no-reply@mail.1mg.com>
28                    Tata 1mg   Rs. 1999.00                                                                                                                                                  with Tata mg Labs is         Tue, 03 Mar                 Tata 1mg <no-reply@mail.1mg.com>
29                    Tata 1mg    Rs. 799.00                                                                                                                                                  with Tata mg Labs is         Tue, 03 Mar                 Tata 1mg <no-reply@mail.1mg.com>
30                    Payments     ₹ 3074.00                                                                                                       Payment successful for 1MG HEALTHCARE SOLUTIONS PRIVATE LIMITED          Tue, 3 Mar                 Payments <no-reply@razorpay.com>
31                  Shiprocket      ₹ 699.00                                                                                                                  Anwesh Biswas, your Rezoni order has been delivered!         Fri, 27 Feb              Shiprocket <info@net.shiprocket.in>
32                  Shiprocket      ₹ 699.00                                                                                                                   Anwesh Biswas, your Rezoni order is arriving early!         Fri, 27 Feb              Shiprocket <info@net.shiprocket.in>
33                  Shiprocket      ₹ 699.00                                                                                                                 Anwesh Biswas, your Rezoni order is out for delivery!         Fri, 27 Feb              Shiprocket <info@net.shiprocket.in>
34                  Shiprocket      ₹ 699.00                                                                                                                Anwesh Biswas your Rezoni order has reached your city.         Fri, 27 Feb              Shiprocket <info@net.shiprocket.in>
35                  Shiprocket      ₹ 699.00                                                                                                                     Anwesh Biswas, your Rezoni order has been picked.         Wed, 25 Feb              Shiprocket <info@net.shiprocket.in>
36                    Tata 1mg         ₹ 242                                                                                                                                   Your test reports are now available         Tue, 24 Feb                 Tata 1mg <no-reply@mail.1mg.com>
37                    Tata 1mg        ₹ 4566                                                                                                                                                         Order ID: PO-         Tue, 24 Feb                 Tata 1mg <no-reply@mail.1mg.com>
38                    Tata 1mg   Rs. 2249.00                                                                                                                                                  with Tata mg Labs is         Tue, 24 Feb                 Tata 1mg <no-reply@mail.1mg.com>
39                  Shiprocket      ₹ 699.00                                                                                                                     Anwesh Biswas, your Rezoni order has been packed!         Tue, 24 Feb              Shiprocket <info@net.shiprocket.in>
40                      Rezoni  Rs. 1,398.00                                                                                                                                               Order #393909 confirmed         Mon, 23 Feb    Rezoni <store+62178296040@t.shopifyemail.com>
41                     Eatclub      ₹ 398.00                                                                                                            Mixed Veg - Light Meal | 4 Ghee Phulkas | 1 Pc 199.0 199.0         Sun, 15 Feb                     Eatclub <noreply@eatclub.in>
42                     Spotify       ₹ 49.00                                                                                                                                   confirmation for "Premium Standard"         Sat, 14 Feb                   Spotify <no-reply@spotify.com>
43            Axis Bank Alerts     INR 49.00                                                                                                                          AutoPay for Spotify India Pvt Ltd: ACTIVATED         Sat, 14 Feb           Axis Bank Alerts <alerts@axis.bank.in>
44                     Eatclub      ₹ 327.00  Fams Favorite Matar Paneer - Feast Thali | Homestyle Yellow Dal [Made in Ghee], 3 Tikona Parathas + Basmati Rice [Half], Mini | Aloo Samosa [Pack of 3], Gajar Halwa         Thu, 22 Jan                     Eatclub <noreply@eatclub.in>
45                     Eatclub      ₹ 549.00                                                                                         Italian Feast Pizza [10" Large]. | Thin Crust Cheese Burst | 1 Pc 549.0 549.0         Sat, 20 Dec                     Eatclub <noreply@eatclub.in>
46                     Eatclub      ₹ 398.00                                                    Weekend Cheat Sheet 1 Pc 0.0 0.0 | Creamy Chicken Mushroom Pasta 1 Pc 299.0 299.0 | Choco Lava Cake 1 Pc 99.0 99.0         Sun, 14 Dec                     Eatclub <noreply@eatclub.in>
47               Cashfree Care     ₹ 4770.15                                                                                                                     REDBUS INDIA PRIVATE LIMITED - Payment successful          Tue, 9 Dec            Cashfree Care <care@cashfreemail.com>
48                     Eatclub      ₹ 269.00                                                                         Homestyle Egg Curry | Dal Makhani, Gajar Halwa, Masala Basmati Rice (Full) | 1 Pc 269.0 269.0          Sun, 7 Dec                     Eatclub <noreply@eatclub.in>
49                     Eatclub      ₹ 249.00                                                                                       Chicken Blaze Pizza - Regular (7") | Thin Crust Cheese Burst | 1 Pc 249.0 249.0          Thu, 4 Dec                     Eatclub <noreply@eatclub.in>
50                     Eatclub      ₹ 318.00                                      Masala Chicken - Feast Thali | Homestyle Yellow Dal [Made in Ghee], 3 Tikona Parathas + Basmati Rice [Half], Mini | Gulab Jamuns         Mon, 17 Nov                     Eatclub <noreply@eatclub.in>
51   PhonePe Insurance Broking       ₹ 11812                                                                                                                                   Your Four Wheeler Insurance details         Fri, 24 Oct  PhonePe Insurance Broking <noreply@phonepe.com>
52           Namecheap Support        $ 0.00                                                                                                                                    Namecheap Order Summary (Order# );         Fri, 09 May        Namecheap Support <support@namecheap.com>
53           Namecheap Support        $ 0.00                                                                                                                                    Namecheap Order Summary (Order# );         Mon, 31 Mar        Namecheap Support <support@namecheap.com>
54                 avni_barman        $ 0.00                                                                                                                       from avni_barman of Proven Cold Email Template!         Thu, 20 Mar              avni_barman <store@info.beacons.ai>
55                  Shiprocket    Rs. 500.00                                                                                                                   Uh-oh! Your recent transaction for Rs.. has failed!         Fri, 22 Nov              Shiprocket <info@net.shiprocket.in>
56                  Shiprocket      ₹ 500.00                                                                                                                                        Shiprocket Credit Confirmation         Fri, 22 Nov              Shiprocket <info@net.shiprocket.in>
57                  Shiprocket     ₹ 1000.00                                                                                                      MR SAHADEB MALLICK, your Anwesh Biswas order has been delivered!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
58                  Shiprocket     ₹ 1000.00                                                                                                          SHRI AJAY UKIL, your Anwesh Biswas order has been delivered!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
59                  Shiprocket     ₹ 1000.00                                                                                                      SHRI SHANTIMAY MAL, your Anwesh Biswas order has been delivered!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
60                  Shiprocket     ₹ 1000.00                                                                                                    SHRI SAMIR KUMAR MAL, your Anwesh Biswas order has been delivered!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
61                  Shiprocket     ₹ 1000.00                                                                                                   SHRI SHANTANU MALLICK, your Anwesh Biswas order has been delivered!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
62                  Shiprocket     ₹ 1000.00                                                                                                  SHRI SHANTANU MALLICK, your Anwesh Biswas order is out for delivery!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
63                  Shiprocket     ₹ 1000.00                                                                                                     SHRI SHANTIMAY MAL, your Anwesh Biswas order is out for delivery!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
64                  Shiprocket     ₹ 1000.00                                                                                                   SHRI SAMIR KUMAR MAL, your Anwesh Biswas order is out for delivery!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
65                  Shiprocket     ₹ 1000.00                                                                                                         SHRI AJAY UKIL, your Anwesh Biswas order is out for delivery!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
66                  Shiprocket     ₹ 1000.00                                                                                                     MR SAHADEB MALLICK, your Anwesh Biswas order is out for delivery!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
67                  Shiprocket     ₹ 1000.00                                                                                                    MR SAHADEB MALLICK your Anwesh Biswas order has reached your city.         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
68                  Shiprocket     ₹ 1000.00                                                                                                        SHRI AJAY UKIL your Anwesh Biswas order has reached your city.         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
69                  Shiprocket     ₹ 1000.00                                                                                                    SHRI SHANTIMAY MAL your Anwesh Biswas order has reached your city.         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>

In [29]:
import os
import pickle
import re
import pandas as pd
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from google.auth.transport.requests import Request

class FinancialScanner:
    def __init__(self):
        self.service = self._get_service()
        # High-signal indicators with weightings
        self.patterns = {
            'bill': 5, 'statement': 5, 'transaction': 4, 
            'debited': 5, 'credited': 5, 'due': 4, 'inr': 2
        }

    def _get_service(self):
        creds = None
        if os.path.exists('token.pickle'):
            with open('token.pickle', 'rb') as token:
                creds = pickle.load(token)
        if not creds or not creds.valid:
            flow = InstalledAppFlow.from_client_secrets_file('credentials.json', ['https://www.googleapis.com/auth/gmail.readonly'])
            creds = flow.run_local_server(port=0)
            with open('token.pickle', 'wb') as token:
                pickle.dump(creds, token)
        return build('gmail', 'v1', credentials=creds)

    def get_financial_score(self, subject, snippet):
        """Scores relevance to ensure only financial emails are processed."""
        text = (subject + snippet).lower()
        score = sum(weight for kw, weight in self.patterns.items() if kw in text)
        return score

    def extract_amount(self, text):
        """Robust currency extraction that handles comma separation and decimal precision."""
        # Finds common currency patterns like '₹ 1,234.56', 'INR 1234', 'Rs. 100'
        match = re.search(r'(?:rs\.?|inr|₹|amount|total)\s*[:\s]*([\d,]+\.?\d*)', text, re.IGNORECASE)
        if match:
            clean_val = match.group(1).replace(',', '')
            try: return float(clean_val)
            except: return 0.0
        return 0.0

    def run_deep_scan(self, max_results=500):
        # Broad scan but restricted to high-probability financial subjects
        query = 'subject:(bill OR transaction OR statement OR debited OR credited OR payment) OR has:attachment'
        results = self.service.users().messages().list(userId='me', q=query, maxResults=max_results).execute()
        messages = results.get('messages', [])
        
        data = []
        for msg in messages:
            try:
                m = self.service.users().messages().get(userId='me', id=msg['id'], format='metadata', metadataHeaders=['From', 'Subject', 'Date']).execute()
                headers = {h['name']: h['value'] for h in m['payload']['headers']}
                snippet = m.get('snippet', '')
                
                # Apply Precision Filter
                if self.get_financial_score(headers.get('Subject', ''), snippet) >= 5:
                    amount = self.extract_amount(snippet)
                    
                    if amount > 0:
                        data.append({
                            'Date': headers.get('Date'),
                            'Amount': amount,
                            'Email Id': re.sub(r'<|>', '', headers.get('From', '').split('<')[-1]),
                            'Context': headers.get('Subject', '')[:60],
                            'Type': self.classify_type(headers.get('Subject', ''), snippet)
                        })
            except Exception: continue
        return pd.DataFrame(data)

    def classify_type(self, subject, snippet):
        text = (subject + snippet).lower()
        if any(k in text for k in ['statement', 'due', 'outstanding']): return 'Credit Card Bill'
        if 'invoice' in text: return 'Invoice'
        if 'bill' in text: return 'Bill'
        return 'Transaction'

if __name__ == "__main__":
    scanner = FinancialScanner()
    df = scanner.run_deep_scan()
    if not df.empty:
        print(df[['Date', 'Amount', 'Email Id', 'Context', 'Type']].to_string(index=False))

                                 Date   Amount                   Email Id                                                      Context             Type
      Tue, 19 May 2026 14:28:32 +0000   300.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 19 May 2026 07:25:22 +0000   192.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 18 May 2026 12:43:01 +0000    20.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 18 May 2026 10:16:41 +0000  7280.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 18 May 2026 10:14:41 +0000    20.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 18 May 2026 15:26:59 +0530  2020.00     statements@rbl.bank.in RBL Bank Paisabazaar Duet Credit Card E-statement dated 17-0 Credit Card Bill
      Sun, 17 May 2026 18:08:12 +0000    59.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Fri, 15 May 2026 18:43:13 +0000    57.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Thu, 14 May 2026 17:02:12 +0000    48.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Wed, 13 May 2026 12:37:41 +0000    49.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Wed, 13 May 2026 09:29:40 +0000   126.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 12 May 2026 18:52:52 +0000    40.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 12 May 2026 16:13:31 +0000   156.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 12 May 2026 15:36:21 +0000    62.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 12 May 2026 13:46:01 +0000    63.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 12 May 2026 08:58:12 +0000   249.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 11 May 2026 20:23:53 +0000    67.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 11 May 2026 14:14:52 +0000    50.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 11 May 2026 09:39:02 +0000   197.89 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 11 May 2026 09:38:11 +0000   183.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sun, 10 May 2026 23:51:42 +0000  1100.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sun, 10 May 2026 16:53:12 +0000 10000.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Sat, 9 May 2026 13:24:13 +0000    30.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Sat, 9 May 2026 06:16:51 +0000   271.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Fri, 8 May 2026 20:21:11 +0000     6.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Fri, 8 May 2026 17:53:43 +0000   550.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Thu, 7 May 2026 19:48:21 +0000    31.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Wed, 6 May 2026 17:31:01 +0000    20.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Wed, 6 May 2026 15:43:31 +0000     1.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Tue, 5 May 2026 08:39:21 +0000    30.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Tue, 5 May 2026 05:17:12 +0000    20.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Mon, 4 May 2026 19:40:02 +0000    10.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Mon, 4 May 2026 17:15:02 +0000   100.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Fri, 1 May 2026 13:27:11 +0000 20550.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 28 Apr 2026 18:49:13 +0000    30.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 28 Apr 2026 18:49:13 +0000    80.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 28 Apr 2026 18:49:13 +0000    80.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sun, 26 Apr 2026 11:53:02 +0000 20000.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sun, 26 Apr 2026 04:17:41 +0000  1000.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sat, 25 Apr 2026 07:08:21 +0000   110.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sat, 25 Apr 2026 06:49:52 +0000   420.36 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Fri, 24 Apr 2026 12:47:51 +0000    62.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Thu, 23 Apr 2026 11:01:21 +0000 27509.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Thu, 23 Apr 2026 10:44:02 +0000    70.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Wed, 22 Apr 2026 17:28:11 +0000 17500.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 21 Apr 2026 18:33:42 +0000   278.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 21 Apr 2026 17:29:01 +0000 26500.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 20 Apr 2026 18:39:33 +0000    59.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 20 Apr 2026 08:00:21 +0000   329.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sat, 18 Apr 2026 18:53:57 +0530  9819.00     statements@rbl.bank.in RBL Bank Paisabazaar Duet Credit Card E-statement dated 17-0 Credit Card Bill
      Thu, 16 Apr 2026 03:18:31 +0000  6000.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 14 Apr 2026 18:44:33 +0530 45000.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 14 Apr 2026 09:40:32 +0000   272.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 14 Apr 2026 09:16:13 +0000    60.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 14 Apr 2026 01:04:43 +0530   300.00      RBLAlerts@rbl.bank.in             Alert: Transaction declined due to incorrect PIN Credit Card Bill
      Fri, 10 Apr 2026 14:33:02 +0000 50500.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Thu, 9 Apr 2026 10:08:12 +0000   400.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Wed, 8 Apr 2026 09:31:12 +0000 60000.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 31 Mar 2026 17:06:33 +0000    44.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 31 Mar 2026 12:18:32 +0000    58.90 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 31 Mar 2026 08:54:04 +0000    26.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 30 Mar 2026 20:13:41 +0000    77.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 30 Mar 2026 17:13:02 +0000   273.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 30 Mar 2026 16:08:32 +0000    89.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sun, 29 Mar 2026 16:30:42 +0000   286.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sat, 28 Mar 2026 08:17:02 +0000    75.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Fri, 27 Mar 2026 17:36:23 +0000   100.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Fri, 27 Mar 2026 17:34:02 +0000    91.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Fri, 27 Mar 2026 07:30:21 +0000   489.03 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Fri, 27 Mar 2026 06:25:02 +0000    27.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Fri, 27 Mar 2026 04:25:41 +0000    65.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Thu, 26 Mar 2026 08:44:11 +0000   175.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Wed, 25 Mar 2026 1:20:18 +0530  1512.84         alerts@rbl.bank.in                One-Time Password for your online transaction      Transaction
       Wed, 25 Mar 2026 1:20:16 +0530  1512.84         alerts@rbl.bank.in                One-Time Password for your online transaction      Transaction
      Wed, 25 Mar 2026 04:40:32 +0000   714.30 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 24 Mar 2026 10:49:09 +0530  4025.00         alerts@rbl.bank.in                One-Time Password for your online transaction      Transaction
      Tue, 24 Mar 2026 22:46:37 +0530  4025.00      RBLAlerts@rbl.bank.in             Alert: Transaction declined due to incorrect PIN Credit Card Bill
      Sun, 22 Mar 2026 07:00:32 +0000   145.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Wed, 18 Mar 2026 07:07:23 +0000    25.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 17 Mar 2026 18:06:11 +0000   166.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sat, 14 Mar 2026 15:41:51 +0000   600.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Wed, 11 Mar 2026 08:56:02 +0000  1345.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Wed, 11 Mar 2026 05:35:53 +0000    81.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Fri, 06 Mar 2026 13:03:20 +0530   674.19      RBLAlerts@rbl.bank.in    Refund Alert - Successfully credited to your card account      Transaction
      Fri, 06 Mar 2026 13:03:15 +0530  1585.59      RBLAlerts@rbl.bank.in    Refund Alert - Successfully credited to your card account      Transaction
      Fri, 06 Mar 2026 13:01:16 +0530   827.22      RBLAlerts@rbl.bank.in    Refund Alert - Successfully credited to your card account      Transaction
       Thu, 5 Mar 2026 17:43:03 +0000   150.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Wed, 4 Mar 2026 15:17:53 +0000    16.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Wed, 4 Mar 2026 14:56:52 +0000   350.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sat, 28 Feb 2026 12:36:49 +0530  9538.00         alerts@rbl.bank.in                One-Time Password for your online transaction      Transaction
       Fri, 27 Feb 2026 8:54:08 +0530  5146.00         alerts@rbl.bank.in                One-Time Password for your online transaction      Transaction
      Wed, 25 Feb 2026 15:59:22 +0000   151.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 23 Feb 2026 14:59:13 +0000   699.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sat, 21 Feb 2026 10:27:42 +0000   671.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sat, 21 Feb 2026 10:26:12 +0000    22.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sat, 21 Feb 2026 10:12:12 +0000  1139.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Mon, 16 Feb 2026 18:11:31 +0000    53.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sat, 14 Feb 2026 20:05:12 +0000   150.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Fri, 13 Feb 2026 20:07:31 +0000    57.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Fri, 13 Feb 2026 20:00:02 +0000   264.65 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Thu, 12 Feb 2026 17:43:34 +0000    50.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Thu, 12 Feb 2026 03:49:53 +0000   135.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 10 Feb 2026 17:58:03 +0000  2000.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 10 Feb 2026 12:46:52 +0000    50.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Tue, 10 Feb 2026 05:00:02 +0000   101.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Mon, 9 Feb 2026 14:38:21 +0000 14500.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
Mon, 09 Feb 2026 04:08:23 +0000 (UTC)    71.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Sun, 8 Feb 2026 11:55:22 +0000   500.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
Sun, 08 Feb 2026 05:54:18 +0000 (UTC)   422.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
Sun, 08 Feb 2026 05:49:41 +0000 (UTC)   425.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Sun, 8 Feb 2026 05:01:01 +0000   120.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Sun, 8 Feb 2026 04:59:32 +0000    50.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Sat, 7 Feb 2026 16:53:54 +0000    20.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
Sat, 07 Feb 2026 14:13:33 +0000 (UTC)    84.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Sat, 7 Feb 2026 06:45:23 +0000   371.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Fri, 6 Feb 2026 17:44:41 +0000   146.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Fri, 6 Feb 2026 16:34:14 +0000   185.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Fri, 6 Feb 2026 11:22:13 +0000  8407.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Fri, 6 Feb 2026 05:41:22 +0000    80.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Wed, 4 Feb 2026 12:13:42 +0000  1084.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Wed, 4 Feb 2026 05:14:52 +0000  1130.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Wed, 4 Feb 2026 03:12:03 +0000   192.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Tue, 3 Feb 2026 11:42:03 +0000    40.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Mon, 2 Feb 2026 19:03:52 +0000    40.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
Mon, 02 Feb 2026 15:40:15 +0000 (UTC)   290.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Sun, 1 Feb 2026 18:59:33 +0000    32.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Sun, 1 Feb 2026 17:41:23 +0000    15.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Sun, 1 Feb 2026 17:39:23 +0000    20.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
       Sun, 1 Feb 2026 17:32:31 +0000    20.00 IndusInd_Bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction
      Sun, 01 Feb 2026 14:12:03 +0530    14.00 indusind_bank@indusind.com                              IndusInd Bank Transaction Alert      Transaction

In [16]:
import os
import pickle
import re
import base64
import io
import pandas as pd
from bs4 import BeautifulSoup
from pypdf import PdfReader
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from google.auth.transport.requests import Request

# Define Scopes
SCOPES = ['https://www.googleapis.com/auth/gmail.readonly']

class FinancialScanner:
    def __init__(self):
        self.service = self._get_service()

    def _get_service(self):
        creds = None
        if os.path.exists('token.pickle'):
            with open('token.pickle', 'rb') as token:
                creds = pickle.load(token)
        if not creds or not creds.valid:
            flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
            with open('token.pickle', 'wb') as token:
                pickle.dump(creds, token)
        return build('gmail', 'v1', credentials=creds)

    def extract_content(self, message_id, payload):
        """Flattens MIME trees and extracts text from HTML and PDF attachments."""
        html_text, pdf_text = "", ""
        stack = [payload]
        while stack:
            part = stack.pop()
            if 'parts' in part:
                stack.extend(part['parts'])
                continue
            
            mime_type = part.get('mimeType', '')
            filename = part.get('filename', '')
            
            if mime_type in ['text/plain', 'text/html'] and not filename:
                data = part.get('body', {}).get('data', '')
                if data:
                    html_text += " " + base64.urlsafe_b64decode(data.encode('ASCII')).decode('utf-8', errors='ignore')
            elif filename.lower().endswith('.pdf') or mime_type == 'application/pdf':
                aid = part.get('body', {}).get('attachmentId')
                if aid:
                    try:
                        att = self.service.users().messages().attachments().get(userId='me', messageId=message_id, id=aid).execute()
                        reader = PdfReader(io.BytesIO(base64.urlsafe_b64decode(att['data'].encode('UTF-8'))))
                        pdf_text += "\n".join([p.extract_text() for p in reader.pages if p.extract_text()])
                    except: pass
        return html_text, pdf_text

    def extract_amount(self, text):
        match = re.search(r'(?:rs\.?|inr|₹|amount|total)\s*[:\s]*([\d,]+\.?\d*)', text, re.IGNORECASE)
        return float(match.group(1).replace(',', '')) if match else 0.0

    def run_deep_scan(self, max_results=100):
        query = 'subject:(bill OR transaction OR statement OR debited OR credited OR payment) OR has:attachment'
        results = self.service.users().messages().list(userId='me', q=query, maxResults=max_results).execute()
        messages = results.get('messages', [])
        
        data = []
        for msg in messages:
            try:
                m = self.service.users().messages().get(userId='me', id=msg['id'], format='full').execute()
                headers = {h['name']: h['value'] for h in m['payload']['headers']}
                html, pdf = self.extract_content(msg['id'], m['payload'])
                full_text = f"{html} {m.get('snippet', '')} {pdf}"
                
                amount = self.extract_amount(full_text)
                if amount > 0:
                    data.append({
                        'Date': headers.get('Date', 'N/A'),
                        'Amount': amount,
                        'Email Id': re.sub(r'<|>', '', headers.get('From', '').split('<')[-1]),
                        'Context': headers.get('Subject', '')[:60],
                        'Type': 'Invoice' if 'invoice' in full_text.lower() else 'Transaction'
                    })
            except: continue
        return pd.DataFrame(data)

# Execution Block
if __name__ == "__main__":
    scanner = FinancialScanner()
    # Save the result to df_inbox
    df_inbox = scanner.run_deep_scan()
    
    # Optional: Save to file for persistence
    df_inbox.to_csv('inbox.csv', index=False)
    
    # Configure display
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_colwidth', None)
    
    print("Scan complete. Access your data using 'df_inbox'.")
    print(df_inbox)

Scan complete. Access your data using 'df_inbox'.
                               Date    Amount                                        Email Id                                                       Context         Type
0   Tue, 19 May 2026 13:05:41 +0530     25.00                        toanweshbiswas@gmail.com  Founder’s Office | Ex-Founder with 0→1 Operational Execution  Transaction
1   Tue, 19 May 2026 13:00:14 +0530     13.00                        toanweshbiswas@gmail.com  Founder’s Office | Ex-Founder with 0→1 Execution & Hyperloca  Transaction
2   Tue, 19 May 2026 07:25:22 +0000    192.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
3   Tue, 19 May 2026 12:38:57 +0530     13.00                        toanweshbiswas@gmail.com  Founder’s Associate / Ops Backbone | Building the infrastruc  Transaction
4   Tue, 19 May 2026 12:09:42 +0530     25.00                        toanweshbiswas@gmail.com  Application: Junior Founder's Office (EA & Strategy) | Ex-Fo  Transaction
5   Mon, 18 May 2026 12:43:01 +0000     20.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
6   Mon, 18 May 2026 10:16:41 +0000   7280.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
7   Mon, 18 May 2026 10:14:41 +0000     20.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
8   Mon, 18 May 2026 15:33:02 +0530   2020.00                           RBLAlerts@rbl.bank.in     Thank you for making Payment on your RBL Bank Credit Card  Transaction
9   Mon, 18 May 2026 15:26:59 +0530   2020.00                          statements@rbl.bank.in  RBL Bank Paisabazaar Duet Credit Card E-statement dated 17-0  Transaction
10  Sun, 17 May 2026 18:08:12 +0000     59.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
11  Fri, 15 May 2026 18:43:13 +0000     57.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
12  Thu, 14 May 2026 17:02:12 +0000     48.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
13  Thu, 14 May 2026 14:51:53 +0530      3.90                        toanweshbiswas@gmail.com  Founder’s Office | Ex-Founder with 0→1 Fintech Execution & R  Transaction
14  Thu, 14 May 2026 14:19:17 +0530     25.00                        toanweshbiswas@gmail.com  Force Multiplier for RagaAI | Ex-Founder with 0→1 Fintech &   Transaction
15  Thu, 14 May 2026 13:32:15 +0530     25.00                        toanweshbiswas@gmail.com  Founder’s Office: Ex-Founder & Vibe Coder ready to scale LH2  Transaction
16  Wed, 13 May 2026 12:37:41 +0000     49.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
17  Wed, 13 May 2026 09:29:40 +0000    126.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
18  Tue, 12 May 2026 18:52:52 +0000     40.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
19  Tue, 12 May 2026 16:13:31 +0000    156.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
20  Tue, 12 May 2026 15:36:21 +0000     62.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
21  Tue, 12 May 2026 13:46:01 +0000     63.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
22  Tue, 12 May 2026 08:58:12 +0000    249.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
23  Mon, 11 May 2026 20:23:53 +0000     67.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
24  Mon, 11 May 2026 14:14:52 +0000     50.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
25  Mon, 11 May 2026 09:39:02 +0000    197.89                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
26  Mon, 11 May 2026 09:38:11 +0000    183.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
27  Sun, 10 May 2026 23:51:42 +0000   1100.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
28  Sun, 10 May 2026 16:53:12 +0000  10000.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
29  Sun, 10 May 2026 08:08:33 +0000   4820.00                             noreply@goibibo.com      E-Ticket for Your Flight Booking ID: GOFLDSTAL3OC6456056      Invoice
30   Sat, 9 May 2026 13:24:13 +0000     30.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
31   Sat, 9 May 2026 06:16:51 +0000    271.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
32   Fri, 8 May 2026 20:21:11 +0000      6.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
33   Fri, 8 May 2026 17:53:43 +0000    550.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
34   Thu, 7 May 2026 19:48:21 +0000     31.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
35   Wed, 6 May 2026 17:31:01 +0000     20.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
36   Wed, 6 May 2026 15:43:31 +0000      1.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
37   Tue, 5 May 2026 08:39:21 +0000     30.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
38   Tue, 5 May 2026 05:17:12 +0000     20.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
39   Mon, 4 May 2026 19:40:02 +0000     10.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
40   Mon, 4 May 2026 17:15:02 +0000    100.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
41  Sun, 03 May 2026 22:31:43 +0530   1860.00                        estatements@indusind.com            Your account statement for the month of April 2026  Transaction
42   Fri, 1 May 2026 13:27:11 +0000  20550.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
43  Fri, 01 May 2026 17:05:43 +0530   9819.00                           RBLAlerts@rbl.bank.in     Thank you for making Payment on your RBL Bank Credit Card  Transaction
44  Tue, 28 Apr 2026 18:49:13 +0000     30.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
45  Tue, 28 Apr 2026 18:49:13 +0000     80.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
46  Tue, 28 Apr 2026 18:49:13 +0000     80.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
47  Tue, 28 Apr 2026 22:46:01 +0530      4.00  noreply-gstinvoice@booking.airindiaexpress.com                GST Invoice for your Air India Express booking      Invoice
48  Sun, 26 Apr 2026 11:53:02 +0000  20000.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
49  Sun, 26 Apr 2026 04:17:41 +0000   1000.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
50  Sat, 25 Apr 2026 07:08:21 +0000    110.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
51  Sat, 25 Apr 2026 06:49:52 +0000    420.36                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
52  Fri, 24 Apr 2026 12:47:51 +0000     62.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
53  Thu, 23 Apr 2026 11:01:21 +0000  27509.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
54  Thu, 23 Apr 2026 10:44:02 +0000     70.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
55  Wed, 22 Apr 2026 17:28:11 +0000  17500.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
56  Tue, 21 Apr 2026 18:33:42 +0000    278.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
57  Tue, 21 Apr 2026 17:29:01 +0000  26500.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
58  Mon, 20 Apr 2026 18:39:33 +0000     59.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
59  Mon, 20 Apr 2026 08:00:21 +0000    329.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
60  Sun, 19 Apr 2026 15:22:45 +0000    263.69                           no-reply@razorpay.com                                 Payment successful for OFFLYN  Transaction
61  Sat, 18 Apr 2026 18:53:57 +0530   9819.00                          statements@rbl.bank.in  RBL Bank Paisabazaar Duet Credit Card E-statement dated 17-0  Transaction
62  Thu, 16 Apr 2026 03:18:31 +0000   6000.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
63  Tue, 14 Apr 2026 18:44:33 +0530  45000.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction

In [15]:
df_purchases

                    Brand Name        Amount                                                                                                                                                    Item / Description Date of Transaction                                  Sender Email ID
0             Axis Bank Alerts    INR 139.00                                                                                                                                        Upcoming AutoPay txn. reminder         Sat, 16 May           Axis Bank Alerts <alerts@axis.bank.in>
1          alerts@axis.bank.in    INR 199.00                                                                                                                                        Upcoming AutoPay txn. reminder         Tue, 12 May      "alerts@axis.bank.in" <alerts@axis.bank.in>
2           Namecheap Renewals       $ 39.18                                                                                                                anwesh, your domains will expire in  hours - renew now         Fri, 08 May      Namecheap Renewals <renewals@namecheap.com>
3           Namecheap Renewals       $ 39.18                                                                                                                 anwesh, your domains will expire in  days - renew now         Sat, 02 May      Namecheap Renewals <renewals@namecheap.com>
4           Namecheap Renewals       $ 39.18                                                                                                                 anwesh, your domains will expire in  days - renew now         Fri, 24 Apr      Namecheap Renewals <renewals@namecheap.com>
5                     Payments      ₹ 263.69                                                                                                                                         Payment successful for OFFLYN         Sun, 19 Apr                 Payments <no-reply@razorpay.com>
6                      Eatclub      ₹ 328.00                                                                           Garden Harvest Pizza - Regular (7") | Thin Crust Cheese Blast, Mushrooms | 1 Pc 328.0 328.0         Tue, 14 Apr                     Eatclub <noreply@eatclub.in>
7           Namecheap Renewals       $ 39.18                                                                                                                 anwesh, your domains will expire in  days - renew now         Thu, 09 Apr      Namecheap Renewals <renewals@namecheap.com>
8           Namecheap Renewals       $ 23.18                                                                                                                 anwesh, goswipe.app will expire in  hours - renew now         Mon, 30 Mar      Namecheap Renewals <renewals@namecheap.com>
9            Namecheap Support        $ 0.00                                                                                                                                    Namecheap Order Summary (Order# );         Sun, 29 Mar        Namecheap Support <support@namecheap.com>
10          Namecheap Renewals       $ 23.18                                                                                                                  anwesh, goswipe.app will expire in  days - renew now         Tue, 24 Mar      Namecheap Renewals <renewals@namecheap.com>
11          Namecheap Renewals       $ 23.18                                                                                                                  anwesh, goswipe.app will expire in  days - renew now         Mon, 16 Mar      Namecheap Renewals <renewals@namecheap.com>
12                     Eatclub      ₹ 268.00                                                                                         Ghee Dal Khichdi Meal 1 Pc 229.0 229.0 | Masala Chaas [200 ml] 1 Pc 39.0 39.0         Sat, 14 Mar                     Eatclub <noreply@eatclub.in>
13                    Tata 1mg        ₹ 1589                                                                                                                                                         Order ID: PO-         Fri, 13 Mar                 Tata 1mg <no-reply@mail.1mg.com>
14                     Eatclub      ₹ 359.00                                                                                                        Herb Chicken Mighty Bowl [64g - High Protein] 1 Pc 359.0 359.0         Thu, 12 Mar                     Eatclub <noreply@eatclub.in>
15                    Payments      ₹ 696.00                                                                                                                  Payment successful for BATRA NUMERRO PRIVATE LIMITED         Thu, 12 Mar                 Payments <no-reply@razorpay.com>
16                    Tata 1mg   Rs. 1399.00                                                                                                                                                  with Tata mg Labs is         Wed, 11 Mar                 Tata 1mg <no-reply@mail.1mg.com>
17                    Payments     ₹ 1345.00                                                                                                       Payment successful for 1MG HEALTHCARE SOLUTIONS PRIVATE LIMITED         Wed, 11 Mar                 Payments <no-reply@razorpay.com>
18                    Tata 1mg         ₹ 122                                                                                                                                   Your test reports are now available         Thu, 05 Mar                 Tata 1mg <no-reply@mail.1mg.com>
19                    Tata 1mg         ₹ 125                                                                                                                                   Your test reports are now available         Thu, 05 Mar                 Tata 1mg <no-reply@mail.1mg.com>
20                    Tata 1mg        ₹ 2087                                                                                                                                                         Order ID: PO-         Thu, 05 Mar                 Tata 1mg <no-reply@mail.1mg.com>
21                    Tata 1mg        ₹ 1998                                                                                                                                                         Order ID: PO-         Thu, 05 Mar                 Tata 1mg <no-reply@mail.1mg.com>
22                    Tata 1mg         ₹ 185                                                                                                                                   Your test reports are now available         Thu, 05 Mar                 Tata 1mg <no-reply@mail.1mg.com>
23                    Tata 1mg        ₹ 4498                                                                                                                                                         Order ID: PO-         Thu, 05 Mar                 Tata 1mg <no-reply@mail.1mg.com>
24                    Tata 1mg    Rs. 799.00                                                                                                                 Sample collection date/time updated for Order ID: PO-         Tue, 03 Mar                 Tata 1mg <no-reply@mail.1mg.com>
25                    Tata 1mg    Rs. 799.00                                                                                                                 Sample collection date/time updated for Order ID: PO-         Tue, 03 Mar                 Tata 1mg <no-reply@mail.1mg.com>
26                    Tata 1mg   Rs. 1999.00                                                                                                                 Sample collection date/time updated for Order ID: PO-         Tue, 03 Mar                 Tata 1mg <no-reply@mail.1mg.com>
27                    Tata 1mg    Rs. 799.00                                                                                                                                                  with Tata mg Labs is         Tue, 03 Mar                 Tata 1mg <no-reply@mail.1mg.com>
28                    Tata 1mg   Rs. 1999.00                                                                                                                                                  with Tata mg Labs is         Tue, 03 Mar                 Tata 1mg <no-reply@mail.1mg.com>
29                    Tata 1mg    Rs. 799.00                                                                                                                                                  with Tata mg Labs is         Tue, 03 Mar                 Tata 1mg <no-reply@mail.1mg.com>
30                    Payments     ₹ 3074.00                                                                                                       Payment successful for 1MG HEALTHCARE SOLUTIONS PRIVATE LIMITED          Tue, 3 Mar                 Payments <no-reply@razorpay.com>
31                  Shiprocket      ₹ 699.00                                                                                                                  Anwesh Biswas, your Rezoni order has been delivered!         Fri, 27 Feb              Shiprocket <info@net.shiprocket.in>
32                  Shiprocket      ₹ 699.00                                                                                                                   Anwesh Biswas, your Rezoni order is arriving early!         Fri, 27 Feb              Shiprocket <info@net.shiprocket.in>
33                  Shiprocket      ₹ 699.00                                                                                                                 Anwesh Biswas, your Rezoni order is out for delivery!         Fri, 27 Feb              Shiprocket <info@net.shiprocket.in>
34                  Shiprocket      ₹ 699.00                                                                                                                Anwesh Biswas your Rezoni order has reached your city.         Fri, 27 Feb              Shiprocket <info@net.shiprocket.in>
35                  Shiprocket      ₹ 699.00                                                                                                                     Anwesh Biswas, your Rezoni order has been picked.         Wed, 25 Feb              Shiprocket <info@net.shiprocket.in>
36                    Tata 1mg         ₹ 242                                                                                                                                   Your test reports are now available         Tue, 24 Feb                 Tata 1mg <no-reply@mail.1mg.com>
37                    Tata 1mg        ₹ 4566                                                                                                                                                         Order ID: PO-         Tue, 24 Feb                 Tata 1mg <no-reply@mail.1mg.com>
38                    Tata 1mg   Rs. 2249.00                                                                                                                                                  with Tata mg Labs is         Tue, 24 Feb                 Tata 1mg <no-reply@mail.1mg.com>
39                  Shiprocket      ₹ 699.00                                                                                                                     Anwesh Biswas, your Rezoni order has been packed!         Tue, 24 Feb              Shiprocket <info@net.shiprocket.in>
40                      Rezoni  Rs. 1,398.00                                                                                                                                               Order #393909 confirmed         Mon, 23 Feb    Rezoni <store+62178296040@t.shopifyemail.com>
41                     Eatclub      ₹ 398.00                                                                                                            Mixed Veg - Light Meal | 4 Ghee Phulkas | 1 Pc 199.0 199.0         Sun, 15 Feb                     Eatclub <noreply@eatclub.in>
42                     Spotify       ₹ 49.00                                                                                                                                   confirmation for "Premium Standard"         Sat, 14 Feb                   Spotify <no-reply@spotify.com>
43            Axis Bank Alerts     INR 49.00                                                                                                                          AutoPay for Spotify India Pvt Ltd: ACTIVATED         Sat, 14 Feb           Axis Bank Alerts <alerts@axis.bank.in>
44                     Eatclub      ₹ 327.00  Fams Favorite Matar Paneer - Feast Thali | Homestyle Yellow Dal [Made in Ghee], 3 Tikona Parathas + Basmati Rice [Half], Mini | Aloo Samosa [Pack of 3], Gajar Halwa         Thu, 22 Jan                     Eatclub <noreply@eatclub.in>
45                     Eatclub      ₹ 549.00                                                                                         Italian Feast Pizza [10" Large]. | Thin Crust Cheese Burst | 1 Pc 549.0 549.0         Sat, 20 Dec                     Eatclub <noreply@eatclub.in>
46                     Eatclub      ₹ 398.00                                                    Weekend Cheat Sheet 1 Pc 0.0 0.0 | Creamy Chicken Mushroom Pasta 1 Pc 299.0 299.0 | Choco Lava Cake 1 Pc 99.0 99.0         Sun, 14 Dec                     Eatclub <noreply@eatclub.in>
47               Cashfree Care     ₹ 4770.15                                                                                                                     REDBUS INDIA PRIVATE LIMITED - Payment successful          Tue, 9 Dec            Cashfree Care <care@cashfreemail.com>
48                     Eatclub      ₹ 269.00                                                                         Homestyle Egg Curry | Dal Makhani, Gajar Halwa, Masala Basmati Rice (Full) | 1 Pc 269.0 269.0          Sun, 7 Dec                     Eatclub <noreply@eatclub.in>
49                     Eatclub      ₹ 249.00                                                                                       Chicken Blaze Pizza - Regular (7") | Thin Crust Cheese Burst | 1 Pc 249.0 249.0          Thu, 4 Dec                     Eatclub <noreply@eatclub.in>
50                     Eatclub      ₹ 318.00                                      Masala Chicken - Feast Thali | Homestyle Yellow Dal [Made in Ghee], 3 Tikona Parathas + Basmati Rice [Half], Mini | Gulab Jamuns         Mon, 17 Nov                     Eatclub <noreply@eatclub.in>
51   PhonePe Insurance Broking       ₹ 11812                                                                                                                                   Your Four Wheeler Insurance details         Fri, 24 Oct  PhonePe Insurance Broking <noreply@phonepe.com>
52           Namecheap Support        $ 0.00                                                                                                                                    Namecheap Order Summary (Order# );         Fri, 09 May        Namecheap Support <support@namecheap.com>
53           Namecheap Support        $ 0.00                                                                                                                                    Namecheap Order Summary (Order# );         Mon, 31 Mar        Namecheap Support <support@namecheap.com>
54                 avni_barman        $ 0.00                                                                                                                       from avni_barman of Proven Cold Email Template!         Thu, 20 Mar              avni_barman <store@info.beacons.ai>
55                  Shiprocket    Rs. 500.00                                                                                                                   Uh-oh! Your recent transaction for Rs.. has failed!         Fri, 22 Nov              Shiprocket <info@net.shiprocket.in>
56                  Shiprocket      ₹ 500.00                                                                                                                                        Shiprocket Credit Confirmation         Fri, 22 Nov              Shiprocket <info@net.shiprocket.in>
57                  Shiprocket     ₹ 1000.00                                                                                                      MR SAHADEB MALLICK, your Anwesh Biswas order has been delivered!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
58                  Shiprocket     ₹ 1000.00                                                                                                          SHRI AJAY UKIL, your Anwesh Biswas order has been delivered!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
59                  Shiprocket     ₹ 1000.00                                                                                                      SHRI SHANTIMAY MAL, your Anwesh Biswas order has been delivered!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
60                  Shiprocket     ₹ 1000.00                                                                                                    SHRI SAMIR KUMAR MAL, your Anwesh Biswas order has been delivered!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
61                  Shiprocket     ₹ 1000.00                                                                                                   SHRI SHANTANU MALLICK, your Anwesh Biswas order has been delivered!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
62                  Shiprocket     ₹ 1000.00                                                                                                  SHRI SHANTANU MALLICK, your Anwesh Biswas order is out for delivery!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
63                  Shiprocket     ₹ 1000.00                                                                                                     SHRI SHANTIMAY MAL, your Anwesh Biswas order is out for delivery!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
64                  Shiprocket     ₹ 1000.00                                                                                                   SHRI SAMIR KUMAR MAL, your Anwesh Biswas order is out for delivery!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
65                  Shiprocket     ₹ 1000.00                                                                                                         SHRI AJAY UKIL, your Anwesh Biswas order is out for delivery!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
66                  Shiprocket     ₹ 1000.00                                                                                                     MR SAHADEB MALLICK, your Anwesh Biswas order is out for delivery!         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
67                  Shiprocket     ₹ 1000.00                                                                                                    MR SAHADEB MALLICK your Anwesh Biswas order has reached your city.         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
68                  Shiprocket     ₹ 1000.00                                                                                                        SHRI AJAY UKIL your Anwesh Biswas order has reached your city.         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>
69                  Shiprocket     ₹ 1000.00                                                                                                    SHRI SHANTIMAY MAL your Anwesh Biswas order has reached your city.         Sun, 17 Nov              Shiprocket <info@net.shiprocket.in>

In [17]:
df_inbox

                               Date    Amount                                        Email Id                                                       Context         Type
0   Tue, 19 May 2026 13:05:41 +0530     25.00                        toanweshbiswas@gmail.com  Founder’s Office | Ex-Founder with 0→1 Operational Execution  Transaction
1   Tue, 19 May 2026 13:00:14 +0530     13.00                        toanweshbiswas@gmail.com  Founder’s Office | Ex-Founder with 0→1 Execution & Hyperloca  Transaction
2   Tue, 19 May 2026 07:25:22 +0000    192.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
3   Tue, 19 May 2026 12:38:57 +0530     13.00                        toanweshbiswas@gmail.com  Founder’s Associate / Ops Backbone | Building the infrastruc  Transaction
4   Tue, 19 May 2026 12:09:42 +0530     25.00                        toanweshbiswas@gmail.com  Application: Junior Founder's Office (EA & Strategy) | Ex-Fo  Transaction
5   Mon, 18 May 2026 12:43:01 +0000     20.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
6   Mon, 18 May 2026 10:16:41 +0000   7280.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
7   Mon, 18 May 2026 10:14:41 +0000     20.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
8   Mon, 18 May 2026 15:33:02 +0530   2020.00                           RBLAlerts@rbl.bank.in     Thank you for making Payment on your RBL Bank Credit Card  Transaction
9   Mon, 18 May 2026 15:26:59 +0530   2020.00                          statements@rbl.bank.in  RBL Bank Paisabazaar Duet Credit Card E-statement dated 17-0  Transaction
10  Sun, 17 May 2026 18:08:12 +0000     59.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
11  Fri, 15 May 2026 18:43:13 +0000     57.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
12  Thu, 14 May 2026 17:02:12 +0000     48.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
13  Thu, 14 May 2026 14:51:53 +0530      3.90                        toanweshbiswas@gmail.com  Founder’s Office | Ex-Founder with 0→1 Fintech Execution & R  Transaction
14  Thu, 14 May 2026 14:19:17 +0530     25.00                        toanweshbiswas@gmail.com  Force Multiplier for RagaAI | Ex-Founder with 0→1 Fintech &   Transaction
15  Thu, 14 May 2026 13:32:15 +0530     25.00                        toanweshbiswas@gmail.com  Founder’s Office: Ex-Founder & Vibe Coder ready to scale LH2  Transaction
16  Wed, 13 May 2026 12:37:41 +0000     49.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
17  Wed, 13 May 2026 09:29:40 +0000    126.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
18  Tue, 12 May 2026 18:52:52 +0000     40.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
19  Tue, 12 May 2026 16:13:31 +0000    156.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
20  Tue, 12 May 2026 15:36:21 +0000     62.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
21  Tue, 12 May 2026 13:46:01 +0000     63.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
22  Tue, 12 May 2026 08:58:12 +0000    249.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
23  Mon, 11 May 2026 20:23:53 +0000     67.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
24  Mon, 11 May 2026 14:14:52 +0000     50.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
25  Mon, 11 May 2026 09:39:02 +0000    197.89                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
26  Mon, 11 May 2026 09:38:11 +0000    183.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
27  Sun, 10 May 2026 23:51:42 +0000   1100.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
28  Sun, 10 May 2026 16:53:12 +0000  10000.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
29  Sun, 10 May 2026 08:08:33 +0000   4820.00                             noreply@goibibo.com      E-Ticket for Your Flight Booking ID: GOFLDSTAL3OC6456056      Invoice
30   Sat, 9 May 2026 13:24:13 +0000     30.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
31   Sat, 9 May 2026 06:16:51 +0000    271.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
32   Fri, 8 May 2026 20:21:11 +0000      6.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
33   Fri, 8 May 2026 17:53:43 +0000    550.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
34   Thu, 7 May 2026 19:48:21 +0000     31.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
35   Wed, 6 May 2026 17:31:01 +0000     20.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
36   Wed, 6 May 2026 15:43:31 +0000      1.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
37   Tue, 5 May 2026 08:39:21 +0000     30.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
38   Tue, 5 May 2026 05:17:12 +0000     20.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
39   Mon, 4 May 2026 19:40:02 +0000     10.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
40   Mon, 4 May 2026 17:15:02 +0000    100.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
41  Sun, 03 May 2026 22:31:43 +0530   1860.00                        estatements@indusind.com            Your account statement for the month of April 2026  Transaction
42   Fri, 1 May 2026 13:27:11 +0000  20550.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
43  Fri, 01 May 2026 17:05:43 +0530   9819.00                           RBLAlerts@rbl.bank.in     Thank you for making Payment on your RBL Bank Credit Card  Transaction
44  Tue, 28 Apr 2026 18:49:13 +0000     30.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
45  Tue, 28 Apr 2026 18:49:13 +0000     80.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
46  Tue, 28 Apr 2026 18:49:13 +0000     80.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
47  Tue, 28 Apr 2026 22:46:01 +0530      4.00  noreply-gstinvoice@booking.airindiaexpress.com                GST Invoice for your Air India Express booking      Invoice
48  Sun, 26 Apr 2026 11:53:02 +0000  20000.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
49  Sun, 26 Apr 2026 04:17:41 +0000   1000.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
50  Sat, 25 Apr 2026 07:08:21 +0000    110.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
51  Sat, 25 Apr 2026 06:49:52 +0000    420.36                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
52  Fri, 24 Apr 2026 12:47:51 +0000     62.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
53  Thu, 23 Apr 2026 11:01:21 +0000  27509.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
54  Thu, 23 Apr 2026 10:44:02 +0000     70.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
55  Wed, 22 Apr 2026 17:28:11 +0000  17500.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
56  Tue, 21 Apr 2026 18:33:42 +0000    278.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
57  Tue, 21 Apr 2026 17:29:01 +0000  26500.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
58  Mon, 20 Apr 2026 18:39:33 +0000     59.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
59  Mon, 20 Apr 2026 08:00:21 +0000    329.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
60  Sun, 19 Apr 2026 15:22:45 +0000    263.69                           no-reply@razorpay.com                                 Payment successful for OFFLYN  Transaction
61  Sat, 18 Apr 2026 18:53:57 +0530   9819.00                          statements@rbl.bank.in  RBL Bank Paisabazaar Duet Credit Card E-statement dated 17-0  Transaction
62  Thu, 16 Apr 2026 03:18:31 +0000   6000.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction
63  Tue, 14 Apr 2026 18:44:33 +0530  45000.00                      IndusInd_Bank@indusind.com                               IndusInd Bank Transaction Alert  Transaction